### PR TITLE
Updating action build app to using swift 5.8

### LINKED ISSUE #189: Update GitHub Action build-app to use swift 5.8
## Description
Need to update the GitHub action [build-app](https://github.com/ios-course/ironfoudation-team-project/blob/main/.github/workflows/build-app.yml) in order to use packages in a project with swift version 5.8

### Dev requirements and restrictions:
Select the version of Xcode for the build that supports swift at least 5.8

## Other useful information
https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md

### PR DESCRIPTION
**Pull request by iBYarchitect**
## Summary
I created a pull request (PR) to update the GitHub Action 'build-app' to use Swift version 5.8.0. This update allows the application's package to be built using Swift 5.8 in the GitHub workflow.
This PR is a part of the work to resolve #189

## Changes
Updated .yml workflow

## Checks to complete
- [x] I've built and run my changes, and no warnings or errors occurred.
- [x] All existing tests passed with my changes.
- [x] My code follows our style guide.
- [x] I've performed a self-review of my code.
- [x] PR's title has a conventional commit style (short and descriptive).
- [x] Every non-private interface is documented properly.
- [x] I've added tests for my code (if it makes sense).
- [x] PR has assignee, reviewers, milestone, it is properly linked to the project and to the issue.

### CODE REVIEW

**Review by NadzeyaShpakouskaya — APPROVED** [review]
LGTM

**Review by marinkman — APPROVED** [review]
LGTM

**Review by julyakmita — APPROVED** [review]
Thanks for quick fixed of this problem.
LGTM!

**Comment by iBYarchitect** [comment]
This PR is closed because the changes were made in another PR #188

**Pull request closed without merging**
