### PR TITLE
Reuses `FiveStarRatingView` into `GeneralInfoSectionView`

### LINKED ISSUE #119: Reuses FiveStarRatingView in GeneralInfoSectionView
## Description
Adds `FiveStarRatingView` in `GeneralInfoSectionView` to show rating.

### PR DESCRIPTION
**Pull request by YuliaNastiushkina**
## Summary
This PR is a part of the work to resolve #119.
Reused `FiveStarRatingView` into `GeneralInfoSectionView` to avoid DRY.

## Checks to complete
- [x] I've built and run my changes, and no warnings or errors occurred.
- [x] All existing tests passed with my changes.
- [x] My code follows our style guide.
- [x] I've performed a self-review of my code.
- [x] PR's title has a conventional commit style (short and descriptive).
- [x] Every non-private interface is documented properly.
- [x] I've added tests for my code (if it makes sense).
- [x] PR has assignee, reviewers, milestone, it is properly linked to the project and to the issue.

### CODE REVIEW

**Review by NadzeyaShpakouskaya — CHANGES_REQUESTED** [review]
Please consider minor improvement

**Review by iBYarchitect — APPROVED** [review]
LGTM

**Review by marinkman — APPROVED** [review]
LGTM

**Review by NadzeyaShpakouskaya — APPROVED** [review]
LGTM

**Pull request merged**
