### PR TITLE
Add schemes for the Woof and WoofTests targets.

### LINKED ISSUE #147: Add build schemes for the Woof and WoofTests targets.
## Description
Add build schemes to the project for the Woof and WoofTests targets. 

## DoD
Add autocreated schemes by Xcode without additional adjusting.

### PR DESCRIPTION
**Pull request by kirpichonok**
## Summary
This PR is a part of the work to resolve #147

## Changes
- Add build scheme for Woof  target.
- Add build scheme for WoofTests target.

## Checks to complete
- [x] I've built and run my changes, and no warnings or errors occurred.
- [x] All existing tests passed with my changes.
- [x] PR's title has a conventional commit style (short and descriptive).
- [x] PR has assignee, reviewers, milestone, it is properly linked to the project and to the issue.

### CODE REVIEW

**Review by marinkman — APPROVED** [review]
LGTM

**Review by NadzeyaShpakouskaya — COMMENTED** [review]
Overal LGTM,
please resolve merge conflict.

**Review by iBYarchitect — COMMENTED** [review]
LGTM

**Review by iBYarchitect — APPROVED** [review]
LGTM

**Pull request merged**
